fast5:
  dir: /disk1/pore_data/MinION_raw_data_20210118
  prefix: DESKTOP_CHF4GRO_20210118_FAP26604_MN21390_sequencing_run_01_18_21_
  names:
    run03: run_03_72958.fast5
  run_splits:
    run03:
    - name: a
      start: 0
      end: 360
segmentation_params:
  out_prefix: /disk1/pore_data/segmented/peptides/20210118
  min_duration_obs: 10
  signal_threshold: 0.700000
  signal_priors:
    prior_open_pore_mean: 220.000000
    prior_open_pore_std: 35.000000
